export const ROLE_PERMISSIONS = {
  Admin: {
    pages: [
      "dashboard",
      "clients",
      "products",
      "suppliers",
      "expenses",
      "labels",
      "scan",
      "categories",
      "quotes",
      "leads",
      "atelier",
      "invoices",
      "creditnotes",
      "sav",
      "automations",
      "users",
      "settings",
      "import",
      "backups",
      "logs",
      "print3dcalc",
      "lasercalc",
      "dtfcalc",
      "uvdtfcalc",
      "brodcalc",
      "vue3d",
      "tshirt3d",
      "banque",
    ],
    canDelete: true,
    canEditSettings: true,
    canManageUsers: true,
    canImport: true,
    actions: {
      delete: true,
      restore: true,
      exportAccounting: true,
      manageUsers: true,
      editSettings: true,
      sendEmails: true,
      viewMargins: true,
    },
  },

  Employé: {
    pages: [
      "dashboard",
      "clients",
      "products",
      "suppliers",
      "expenses",
      "labels",
      "scan",
      "quotes",
      "leads",
      "atelier",
      "invoices",
      "creditnotes",
      "sav",
      "automations",
      "banque",
      "print3dcalc",
      "lasercalc",
      "dtfcalc",
      "uvdtfcalc",
      "brodcalc",
      "tshirt3d",
      "vue3d",
    ],
    canDelete: false,
    canEditSettings: false,
    canManageUsers: false,
    canImport: false,
    actions: {
      delete: false,
      restore: false,
      exportAccounting: false,
      manageUsers: false,
      editSettings: false,
      sendEmails: true,
      viewMargins: true,
    },
  },

  Comptable: {
    pages: ["dashboard", "invoices", "creditnotes", "expenses", "banque", "automations"],
    canDelete: false,
    canEditSettings: false,
    canManageUsers: false,
    canImport: false,
    actions: {
      delete: false,
      restore: false,
      exportAccounting: true,
      manageUsers: false,
      editSettings: false,
      sendEmails: true,
      viewMargins: true,
    },
  },

  Utilisateur: {
    pages: ["dashboard"],
    canDelete: false,
    canEditSettings: false,
    canManageUsers: false,
    canImport: false,
    actions: {
      delete: false,
      restore: false,
      exportAccounting: false,
      manageUsers: false,
      editSettings: false,
      sendEmails: false,
      viewMargins: false,
    },
  },
};

export function getPermissions(role) {
  return ROLE_PERMISSIONS[role] || ROLE_PERMISSIONS.Utilisateur;
}

export function canPerformAction(role, action) {
  return Boolean(getPermissions(role).actions?.[action]);
}
