import { describe, expect, it } from "vitest";
import { strToU8, zipSync } from "fflate";
import {
  buildCalcFormPatchFromImport,
  gramsFromLengthMeters,
  parse3mfBuffer,
  parseDurationToMinutes,
  parseGcodeText,
  parseSlicerBuffer,
  projectNameFromPath,
} from "./slicerFileImport";

function make3mfArchive(files) {
  const entries = {};
  for (const [path, content] of Object.entries(files)) {
    entries[path] = strToU8(content);
  }
  return zipSync(entries);
}

describe("slicerFileImport helpers", () => {
  it("convertit une durée Bambu/Orca en minutes", () => {
    expect(parseDurationToMinutes("2h 36m 25s")).toBeCloseTo(156.416, 2);
    expect(parseDurationToMinutes("1d 8h 29m 45s")).toBeCloseTo(1949.75, 2);
    expect(parseDurationToMinutes("45m 10s")).toBeCloseTo(45.166, 2);
  });

  it("estime les grammes depuis une longueur filament", () => {
    const grams = gramsFromLengthMeters(14.664, 1.75, 1.25);
    expect(grams).toBeGreaterThan(40);
    expect(grams).toBeLessThan(50);
  });

  it("extrait le nom projet depuis un chemin Windows", () => {
    expect(projectNameFromPath("C:\\Users\\test\\SupportTelephone.3mf")).toBe("SupportTelephone");
  });
});

describe("parseGcodeText", () => {
  it("lit filament, durée et nom depuis un G-code Orca/Prusa", () => {
    const gcode = `
; generated by OrcaSlicer
; estimated printing time (normal mode) = 2h 15m 0s
; filament used [g] = 22.5
; filament used [g] = 10.0
; model name: Boitier ESP32
G28
`;

    const result = parseGcodeText(gcode, "job.gcode");
    expect(result.success).toBe(true);
    expect(result.totalGrams).toBeCloseTo(32.5, 1);
    expect(result.printTimeHours).toBeCloseTo(2.25, 2);
    expect(result.projectName).toBe("Boitier ESP32");
    expect(result.warnings.some((w) => w.includes("2 filaments"))).toBe(true);
  });

  it("lit un G-code Bambu Studio (durée header, longueur si pas de poids)", () => {
    const gcode = `
; HEADER_BLOCK_START
; BambuStudio 01.09.00.70
; model printing time: 1h 20m 0s; total estimated time: 1h 25m 0s
; filament_density: 1.25
; filament_diameter: 1.75
; HEADER_BLOCK_END
; filament used [mm] = 14664.38
G28
`;

    const result = parseGcodeText(gcode, "piece.gcode");
    expect(result.success).toBe(true);
    expect(result.printTimeMinutes).toBeCloseTo(80, 1);
    expect(result.totalGrams).toBeGreaterThan(40);
    expect(result.projectName).toBe("piece");
  });

  it("échoue proprement si aucune donnée utile", () => {
    const result = parseGcodeText("; empty file\nG28", "vide.gcode");
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/Impossible d'extraire/i);
  });
});

describe("parse3mfBuffer", () => {
  it("lit slice_info.config Bambu (filament used_g + durée)", () => {
    const archive = make3mfArchive({
      "Metadata/slice_info.config": `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <header>
    <prediction>2h 10m 0s</prediction>
  </header>
  <plate>
    <filament id="0" type="PLA" color="#FFFFFF" used_m="1200.5" used_g="45.2"/>
    <filament id="1" type="PLA" color="#000000" used_m="300.0" used_g="11.3"/>
  </plate>
</config>`,
      "Metadata/model_settings.config": `{
  "name": "Support Phone",
  "from": "C:\\\\Users\\\\test\\\\Support Phone.3mf"
}`,
    });

    const result = parse3mfBuffer(archive, "export.3mf");
    expect(result.success).toBe(true);
    expect(result.projectName).toBe("Support Phone");
    expect(result.totalGrams).toBeCloseTo(56.5, 1);
    expect(result.printTimeHours).toBeCloseTo(2.166, 2);
    expect(result.warnings.some((w) => w.includes("2 filaments"))).toBe(true);
  });

  it("estime le poids depuis used_m si used_g vaut 0", () => {
    const archive = make3mfArchive({
      "Metadata/slice_info.config": `<config>
  <plate>
    <filament id="0" type="PLA" used_m="14.664" used_g="0"/>
  </plate>
</config>`,
      "Metadata/project_settings.config": `"default_filament_diameter": "1.75"
"default_filament_density": "1.25"`,
    });

    const result = parse3mfBuffer(archive, "cli-slice.3mf");
    expect(result.success).toBe(true);
    expect(result.totalGrams).toBeGreaterThan(40);
    expect(result.warnings.some((w) => w.includes("estimé"))).toBe(true);
  });

  it("refuse un 3MF sans métadonnées de tranche", () => {
    const archive = make3mfArchive({
      "3D/3dmodel.model": "<model/>",
    });

    const result = parse3mfBuffer(archive, "unsliced.3mf");
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/Aucune donnée de tranche/i);
  });
});

describe("parseSlicerBuffer + buildCalcFormPatchFromImport", () => {
  it("route selon l'extension", () => {
    const gcode = strToU8(`; total filament used [g] = 12.0\n; estimated printing time (normal mode) = 1h 0m 0s\n`);
    const result = parseSlicerBuffer(gcode, "test.gcode");
    expect(result.sourceType).toBe("gcode");
    expect(result.totalGrams).toBe(12);
  });

  it("refuse les formats inconnus", () => {
    const result = parseSlicerBuffer(strToU8("data"), "file.stl");
    expect(result.success).toBe(false);
    expect(result.error).toMatch(/Format non pris en charge/i);
  });

  it("produit un patch pour le formulaire calcul", () => {
    const patchResult = buildCalcFormPatchFromImport({
      success: true,
      projectName: "Test",
      totalGrams: 55.5,
      printTimeHours: 2.5,
      partial: false,
      warnings: [],
    });

    expect(patchResult.patch).toEqual({
      projectName: "Test",
      grams: 55.5,
      hours: 2.5,
    });
    expect(patchResult.toastType).toBe("success");
  });
});
